# Generated by Django 5.2.15 on 2026-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement_key", models.CharField(max_length=100)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
