# Generated by Django 5.2.15 on 2026-06-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0002_seed_movements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
