# Generated by Django 5.2.15 on 2026-06-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0003_alter_workout_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
