# Generated by Django 5.2.15 on 2026-06-15 01:20

from django.db import migrations, models
from django.db.models import F


def confirm_existing_workouts(apps, schema_editor):
    """Existing workouts predate the draft concept; treat them as confirmed.

    Backfilling confirmed_at = created_at keeps everyone's history counting
    toward gems and achievements instead of silently un-counting it.
    """
    Workout = apps.get_model("workouts", "Workout")
    Workout.objects.filter(confirmed_at__isnull=True).update(
        confirmed_at=F("created_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0004_workout_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(confirm_existing_workouts, migrations.RunPython.noop),
    ]
