# Generated by Django 5.2.15 on 2026-06-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_workout_confirmed_at"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="cardioexercise",
            name="cardio_exercise_requires_distance_or_duration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("distance__isnull", False),
                    ("duration__isnull", False),
                    _connector="OR",
                ),
                name="cardio_exercise_requires_distance_or_duration",
                violation_error_message="Enter at least one of distance or duration.",
            ),
        ),
    ]
